// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "b015d86f-63b1-4dba-844d-de670d0fdad0";   //b015d86f-63b1-4dba-844d-de670d0fdad0   6f527afd-85d6-421e-a72e-fe3589575848

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFlagCloudChange();

int lockChart;
bool flagCloud;
bool lockCloud;
bool bell; 

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lockChart, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(flagCloud, READWRITE, ON_CHANGE, onFlagCloudChange);
  ArduinoCloud.addProperty(lockCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(bell, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
